[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.77"
sea-orm = "0.12.10"
thiserror = "1.0.52"
clap = { version = "4.4.11", features = ["derive"] }
